language: cpp
branches:
  only:
  - travis
install:
  - cd /tmp
  - git clone https://github.com/h2o/picotls.git && cd picotls
  - git submodule init && git submodule update
  - cmake . && make && make check
  - cd $TRAVIS_BUILD_DIR && make