matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

language: cpp

branches:
  only:
  - travis

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - cd /tmp
  - git clone https://github.com/h2o/picotls.git && cd picotls
  - git submodule init && git submodule update
  - cmake . && make && make check
  - cd $TRAVIS_BUILD_DIR && make