language: cpp
branches:
  only:
  - travis
install:
  - wget https://github.com/h2o/picotls/archive/d94a67d4d9733fa7b72c331d238c6160298d39b3.zip -O /tmp/picotls.zip
  - unzip /tmp/picotls.zip
  - cd /tmp/picotls-d94a67d4d9733fa7b72c331d238c6160298d39b3 && cmake . && make && make check